CREATE DATABASE wisudascan_db;
USE wisudascan_db;

DROP TABLE IF EXISTS dataabsensi;
DROP TABLE IF EXISTS users;

/* 1. Hapus aturan UNIQUE yang salah dari kolom noAbsen */
ALTER TABLE dataabsensi DROP INDEX noAbsen;

/* 2. Tambahkan aturan UNIQUE baru untuk kombinasi (noAbsen, kelas) */
ALTER TABLE dataabsensi ADD UNIQUE KEY unik_siswa_per_kelas (noAbsen, kelas);

CREATE TABLE dataabsensi (
	id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    kelas VARCHAR (20) NOT NULL,
    noAbsen INT NOT NULL,
    waktuScan DATETIME NULL DEFAULT NULL,
    status ENUM ('Hadir', 'Absen') NOT NULL DEFAULT 'Absen',
    
    UNIQUE KEY absen_unique (noAbsen, kelas)
);

CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR (255),
    password VARCHAR(255)
);

INSERT INTO users (email, password) 
VALUES 
('adminabsensi@gmail.com', 'wisudascan123');

/* Data untuk XII 1 */
INSERT INTO dataabsensi (nama, kelas, noAbsen) 
VALUES
('ABDUL WADUD SYALABHI', 'XII 1', 1),
('ADE AULIA SRI HARTATI', 'XII 1', 2),
('ADE AYU PUTRI CAHYADI', 'XII 1', 3),
('AIGGAR ZHOOHIR QOWIYY OKTARA', 'XII 1', 4),
('ALFIRA ZALIANTY', 'XII 1', 5),
('ALIN ANGGRAINI', 'XII 1', 6),
('ALISYA', 'XII 1', 7),
('ALVAN HADIAN', 'XII 1', 8),
('ANNISA PUTRI DWI ARDININGRUM', 'XII 1', 9),
('ARIF FATHURROHMAN', 'XII 1', 10),
('CITRA WIDYA MAHARANI', 'XII 1', 11),
('DAMIAN ZIDNY ARDIANSYAH', 'XII 1', 12),
('DIAZ AZKIYA PURBA', 'XII 1', 13),
('DIVA NUR AISYAH', 'XII 1', 14),
('FATHUR RAHMAN AKMAL', 'XII 1', 15),
('FATIMAH TUZAHRA', 'XII 1', 16),
('GADIS MAHARANI MUTIARA AYUNING SARI', 'XII 1', 17),
('GADIZA AYU AFIANI', 'XII 1', 18),
('INTAN ALUNA PRAMESWARI', 'XII 1', 19),
('JESIKA RAHMA NITA', 'XII 1', 20),
('KAYLA CHERYL KURNIA', 'XII 1', 21),
('LUBNA KHAIRUNNISA', 'XII 1', 22),
('MAYLIKA KHARISMA SETIAWAN', 'XII 1', 23),
('MUHAMAD NUR IHSAN', 'XII 1', 24),
('MUHAMMAD ATHAURRAHMAN', 'XII 1', 25),
('NATANAEL TIOPAN NICOLAS PUTRA SIAHAAN', 'XII 1', 26),
('NUR SYAHIRA', 'XII 1', 27),
('PANJI WELLINGTON PUTRA KURNIAWAN', 'XII 1', 28),
('RAFA AGUNG IDHA', 'XII 1', 29),
('RAFAEL BENAYA THESALONICO SIBURIAN', 'XII 1', 30),
('RAIDA MUFIDAH HAKIM', 'XII 1', 31),
('REVAL DIMAS JODI', 'XII 1', 32),
('SEKAR KEDATON', 'XII 1', 33),
('SINTIA MAHA RANI', 'XII 1', 34),
('THALITA NUR SHABRINA', 'XII 1', 35),
('ZAHRA ZIHABI', 'XII 1', 36);

/* Data untuk XII 2 */
INSERT INTO dataabsensi (nama, kelas, noAbsen) 
VALUES
('AKBAR SATRYO KRISDIYANTO', 'XII 2', 1),
('ALRASYAH SYAHRAN CONERI', 'XII 2', 2),
('ARYO KRISHNA RAMADHAN', 'XII 2', 3),
('AZIMA ANASTASYA ZAIDA', 'XII 2', 4),
('AZKA ACHMAD AUFA', 'XII 2', 5),
('BALQIS LUTFIAH ADIBA', 'XII 2', 6),
('DEHATYA NATASYA MURDISARI', 'XII 2', 7),
('DEWI SAHIRAH', 'XII 2', 8),
('ERLA AYUDITA', 'XII 2', 9),
('FARAH ZEA AUREOLA HANIEF', 'XII 2', 10),
('FARHAN RESKI WIDYPUTRA', 'XII 2', 11),
('INDANA HALWAH RAQIQAH', 'XII 2', 12),
('IRENE ANASTASYA', 'XII 2', 13),
('ISDAWANTINO AHMAD DELMI', 'XII 2', 14),
('JANECIA R. P. C. MEWENGKANG', 'XII 2', 15),
('JULIUS WIRA YOHANES SILALAHI', 'XII 2', 16),
('KEYLA CINTA MAHARANI', 'XII 2', 17),
('KHOIRUL FAHREZI', 'XII 2', 18),
('LUTFIAH NUR AZIZAH', 'XII 2', 19),
('MAHAKA ARKANANTA SADEWA', 'XII 2', 20),
('MUHAMMAD ALIEF SALIM', 'XII 2', 21),
('MUHAMMAD EVAN ROHMATUL U', 'XII 2', 22),
('MUHAMMAD GHIFARI AL RASHID', 'XII 2', 23),
('MUHAMMAD RAFIF BASYARACH', 'XII 2', 24),
('MUHAMMAD SHADIQ ISTHOFA', 'XII 2', 25),
('MUHAMMAD ZAKY YUNANTO', 'XII 2', 26),
('NABILLAH MASAYU PUTRI HARA', 'XII 2', 27),
('NABIL EZHAR ARKANANTA', 'XII 2', 28),
('NAFISHA AZALIA GIRI', 'XII 2', 29),
('NAIRA KUSUMAWARDHANI NUGROHO', 'XII 2', 30),
('RADHITYA PRATAMA', 'XII 2', 31),
('RADITHYA FARRAS ABDULLAH', 'XII 2', 32),
('RIFKIANDRA HARSIFAREL', 'XII 2', 33),
('SUNAJI', 'XII 2', 34),
('TSABITAH ADITIA PRATIWI', 'XII 2', 35),
('WAHYU ANGGARA PUTRA', 'XII 2', 36);

/* Data untuk XII 3 */
INSERT INTO dataabsensi (nama, kelas, noAbsen)
VALUES
('ABDUL ROHMAN', 'XII 3', 1),
('ADIESTY SAHARA', 'XII 3', 2),
('AGISTA HANIF', 'XII 3', 3),
('ANANDA AULIA ROSMAWATI', 'XII 3', 4),
('ASEP SAPUTRA', 'XII 3', 5),
('AURELLIA HUMAIRA ESYADHA PUTRI', 'XII 3', 6),
('CHOIRUNNISA', 'XII 3', 7),
('DWI CHANDRA EKA TAMA', 'XII 3', 8),
('FARAH DIBAH', 'XII 3', 9),
('FEBRIAN CITRA NUSANTARA', 'XII 3', 10),
('FEBRIAN MAULANA', 'XII 3', 11),
('HOTMAN ALFA CHRISTIAN SITOHANG', 'XII 3', 12),
('IMAM RAHMAT DHANI', 'XII 3', 13),
('JALILAH', 'XII 3', 14),
('JIHAN ANLY ZATMIKO', 'XII 3', 15),
('KANIA ALIFIA', 'XII 3', 16),
('MISBACH HUSSABIL', 'XII 3', 17),
('MUHAMAD ANDIKA SAPUTRA', 'XII 3', 18),
('MUHAMMAD ADIP AZ ZUFAR', 'XII 3', 19),
('MUHAMMAD RAFFI ALFASSYAH', 'XII 3', 20),
('MUHIDIN YANSA', 'XII 3', 21),
('MULAN SAVITRI', 'XII 3', 22),
('NABILA SALSABILA', 'XII 3', 23),
('NAIMAH', 'XII 3', 24),
('NANDA AYU CIPTA LESTARI', 'XII 3', 25),
('RAYA DARA OKTAVIANI', 'XII 3', 26),
('REZA OCTA RAMADHAN', 'XII 3', 27),
('RIFAT FABIAN HADI', 'XII 3', 28),
('RIZKIAN JANSSEN', 'XII 3', 29),
('RIZKY DARREN ROMANSA', 'XII 3', 30),
('SATRIA RAMADHAN', 'XII 3', 31),
('SRI WAHYUNI', 'XII 3', 32),
('SUCI NURUL HUDA', 'XII 3', 33),
('SURYA FEBRIYAN', 'XII 3', 34),
('YESA SEKHINA GLORI BURNAMA', 'XII 3', 35);

/* Data untuk XII 4 */
INSERT INTO dataabsensi (nama, kelas, noAbsen)
VALUES
('ABDUL AZIZ AL QOIM MUSHTHOFA', 'XII 4', 1),
('ADINDA PUTRI NAILAH RANGKUTI', 'XII 4', 2),
('AHMAD BAIHAKI', 'XII 4', 3),
('AJIE PANGESTU', 'XII 4', 4),
('AL FATHIR PASHA HARLEY ROSS', 'XII 4', 5),
('ALDY FEBRIYANSYAH', 'XII 4', 6),
('ALIFAH AGUSTINA', 'XII 4', 7),
('ARIEL DWI SEPTIYANTO', 'XII 4', 8),
('ARKALEON BANYU SAMUDRA', 'XII 4', 9),
('AURA SHAFIA UTAMA', 'XII 4', 10),
('AURELIA KAYLA DIVA', 'XII 4', 11),
('DAFA SETIAWAN', 'XII 4', 12),
('DAVIN SATRYAWAN', 'XII 4', 13),  
('DHIYA NISTRINA', 'XII 4', 14),
('DZAKI SYAFIQ WICAKSONO', 'XII 4', 15),
('FASIHULLISAN', 'XII 4', 16),
('FIRDHA SALSABILLAH MAKASSAR', 'XII 4', 17),
('IMELDA TANTHEO', 'XII 4', 18),
('IQBAL SYAHRUL ALAM', 'XII 4', 19),
('JANUAR ELFANO RADEWA', 'XII 4', 20),
('KALISA RISKY SAPUTRO', 'XII 4', 21),
('MALIQA ALMAQHVIRA ASSYARBY', 'XII 4', 22),
('MIRDA DIANNA ELVIRA', 'XII 4', 23),
('MUHAMMAD RASSYA NUR ISLAMY R', 'XII 4', 24),
('MUHAMMAD SABILA MUKLIS', 'XII 4', 25),
('NADYA RULIANNI SYAFIRA GULTOM', 'XII 4', 26),
('NAILA PUTRI ANJANI BASRI', 'XII 4', 27),
('NASYA AZARIA MUMTAZ', 'XII 4', 28),
('NUR YULITA LESTARI', 'XII 4', 29),
('PANJI ARDIANSYAH', 'XII 4', 30),
('QONITA AISYAH PUTRI', 'XII 4', 31),
('RAFA ELVARO', 'XII 4', 32),
('RAFA MUHAMMAD REINARDO PUTRA', 'XII 4', 33),
('SISKA AMELIA', 'XII 4', 34),
('YUNITA FEBRIANI', 'XII 4', 35),
('ZASKIA RIANASARI', 'XII 4', 36);

/* Data untuk XII 5 */
INSERT INTO dataabsensi (nama, kelas, noAbsen)
VALUES
('ADITIA NUGRAHA', 'XII 5', 1),
('AKIFAH HAJIDAH', 'XII 5', 2),
('ALBAR RIZKY YANTO', 'XII 5', 3),
('ALWAN ASSYAUQI', 'XII 5', 4),
('ALWAN MUAFI RAMADHAN', 'XII 5', 5),
('AUFA ALFIAH HAKIM', 'XII 5', 6),
('DAYUS EZA SUGIARTO', 'XII 5', 7),
('EMANUEL GRACIO AGNOV TAMPUBOLON', 'XII 5', 8), 
('FARIS HAFIIDZ KAMALUDDIN', 'XII 5', 9),
('FIKRI SYACHRUL ROMADHANA', 'XII 5', 10),
('HANIF SOFYANA SAIF', 'XII 5', 11),
('HERBAYU LUKMAN ASHADI', 'XII 5', 12),
('JIDDAN MAULANA', 'XII 5', 13),
('KHESYA ANDIRA PUTRI', 'XII 5', 14),
('LUTHFIYA ZAHRA MARICAR', 'XII 5', 15),
('MUAMAR KHADAFI', 'XII 5', 16),
('MUHAMAD FAUZAN RIJAL ARSYI', 'XII 5', 17),
('MUHAMAD GUNTUR BAGINDA', 'XII 5', 18),
('MUHAMAD RAIHAN FIRDAUS', 'XII 5', 19),
('MUHAMAD RIFKI SALIK', 'XII 5', 20),
('MUHAMMAD ADLY FAYRUZ', 'XII 5', 21),
('MUHAMMAD AR RIDHO', 'XII 5', 22),
('MUHAMMAD FADLAN', 'XII 5', 23),
('MUHAMMAD FIRJATULLAH DZAKHWAN', 'XII 5', 24),
('MUHAMMAD NABIL RAMADHAN', 'XII 5', 25),
('MUHAMMAD RIZKI', 'XII 5', 26),
('RACHEL ANGELINA DEBORA SITUNGKIR', 'XII 5', 27), 
('RAFA CHAIRUNNISA', 'XII 5', 28),
('RAFA HAFIER ALFARIZY', 'XII 5', 29),
('RAFI AKHBAR IDHA', 'XII 5', 30),
('RAINA LYDIA CALYSTA NADESDA PANGGABEAN', 'XII 5', 31), 
('RIDO FEBRIANSYAH', 'XII 5', 32),
('SALMAN ALI ALFARIZI', 'XII 5', 33),
('SHAFA ALYA ZAHIRAH', 'XII 5', 34),
('SITI RAMISA GHALIYA', 'XII 5', 35),
('ZHARA MARSELLA BR PERANGIN-ANGIN', 'XII 5', 36);

/* Data untuk XII 6 */
INSERT INTO dataabsensi (nama, kelas, noAbsen)
VALUES
('ABDUL ROHIM', 'XII 6', 1),
('ADRIAN OKTAVIAN RAMADHAN', 'XII 6', 2),
('AHMAD ARRIZKY', 'XII 6', 3),
('ALFIYA PUTRI NEISKHA', 'XII 6', 4),
('ARVIA RIZQINA ARRUMMAISHA', 'XII 6', 5),
('ASHROTUL KAYLA ISTIQOMAH', 'XII 6', 6),
('ATHA ILLAHNO RAMADHANI WAHID', 'XII 6', 7),
('AULIA SHINTA MULYAWATI', 'XII 6', 8),
('CAHAYA KIRANI', 'XII 6', 9),
('CHELSE MARSYAH', 'XII 6', 10),
('DEVINA ZALFA NAZHIFA', 'XII 6', 11),
('DOUGLAS WILLIAMSEN DOTULONG', 'XII 6', 12),
('DZIKRY ZARKASYI', 'XII 6', 13),
('INTAN ALAYKA AZZAHRA', 'XII 6', 14),
('IQBAL FAUZAN', 'XII 6', 15),
('IRENA RIZKIANY AZ ZAHRA', 'XII 6', 16),
('JOHN WESLY SIMANJUNTAK', 'XII 6', 17),
('KEISHA KHIRANI MONICA PURNOMO', 'XII 6', 18),
('MANDA ROSITA', 'XII 6', 19),
('MARSHALL RAFAEL ARSENAL JACOB', 'XII 6', 20),
('MARSYA ZALPA AZAHRA', 'XII 6', 21),
('MARYAM', 'XII 6', 22),
('MUHAMAD RAJJA', 'XII 6', 23),
('MUHAMMAD ASWAN FABIAN', 'XII 6', 24),
('MUHAMMAD RIFQI', 'XII 6', 25),
('QAULAN SADIDAN', 'XII 6', 26),
('RAFFY INDRA OKTAVIAN', 'XII 6', 27),
('RAISYA NUR SHIFA', 'XII 6', 28),
('RAMDA EKA SAPUTRA', 'XII 6', 29),
('RASYA', 'XII 6', 30),
('RHESPATI YUDHO UTOMO', 'XII 6', 31),
('SAFIRA DAMAYANTI', 'XII 6', 32),
('SAMBA SATRIA PRATAMA', 'XII 6', 33),
('SHAFIRA JULIANT SUMMAYYAH', 'XII 6', 34),
('TASYA ANGGRAINI', 'XII 6', 35);

/* Data untuk XII 7 */
INSERT INTO dataabsensi (nama, kelas, noAbsen)
VALUES
('AIDA IZZATI TAMIMAH ADHI', 'XII 7', 1),
('ALDO ARDIANSYAH', 'XII 7', 2),
('ALVERIO MAHADIKA DHARMA', 'XII 7', 3),
('ANISYAH', 'XII 7', 4),
('ANNISA FATIMAH NUR SUDARGO', 'XII 7', 5),
('AULIA SARI', 'XII 7', 6),
('AULIYA SETYAWAN', 'XII 7', 7),
('BAGAS SYAKIEB MANANDI', 'XII 7', 8),
('BVIENO RASYA PUTRA ALFIANO', 'XII 7', 9),
('CHALISTA FAHMI AQILAH', 'XII 7', 10),
('DEVITA ANGGRAINI', 'XII 7', 11),
('DWI ADITIYA SAPUTRA', 'XII 7', 12),
('EARLY AZARIA NUR AZIZAH', 'XII 7', 13),
('EUDORA RICHY SETYADY', 'XII 7', 14),
('FEBRIYANTI LESTARI', 'XII 7', 15),
('GHISELLA NATALI TAMBUNAN', 'XII 7', 16),
('JASON MEYER', 'XII 7', 17),
('KEYSHA FEBRIA PUTRI', 'XII 7', 18),
('KHEYSHA ADELIA PUTRI', 'XII 7', 19),
('MARSHAL TRI HENDRAWAN', 'XII 7', 20),
('MUHAMMAD ALFAREZEL', 'XII 7', 21),
('MUHAMMAD FADLI HARFIDAYANSYAH', 'XII 7', 22),
('MUHAMMAD FAUZAN SAPUTRA', 'XII 7', 23),
('MUHAMMAD NAUFAL STAQIF', 'XII 7', 24),
('MUHAMMAD RIFAI', 'XII 7', 25),
('MUHAMMAD RIZKI', 'XII 7', 26),
('MUTTIA BALGIS', 'XII 7', 27),
('NICHOLAS DAFFA SAPUTRA', 'XII 7', 28),
('RIDWAN RAMADHANI', 'XII 7', 29),
('SALMAN ALFARIS', 'XII 7', 30),
('SALWA FEBRIYANI', 'XII 7', 31),
('SATRIA GEN ARASY', 'XII 7', 32),
('SATRIA RAMADHAN', 'XII 7', 33),
('SRI NURLAILA', 'XII 7', 34),
('VARREL WIRANATA', 'XII 7', 35),
('ZARRAH ELMALIYA DIKA', 'XII 7', 36);

SHOW TABLES;
SELECT * FROM users;
SELECT * FROM dataabsensi;




